# Generated by Django 4.2.3 on 2024-04-29 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=255)),
                ('siglas', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_value', models.TextField(default='', max_length=2000)),
                ('native_value', models.CharField(default='', max_length=2000)),
                ('language_trans', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='translate.language')),
            ],
        ),
        migrations.CreateModel(
            name='Translate_relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_translate', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='card.card')),
                ('menu_translate', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.menuitem')),
                ('translate', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='translate.translate')),
            ],
        ),
    ]
