# Generated by Django 4.2.3 on 2023-08-02 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_rename_tittle_card_title'),
        ('home', '0016_menuitem_button_menuitem_divider_and_more'),
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translate',
            name='card_translate',
        ),
        migrations.RemoveField(
            model_name='translate',
            name='menu_translate',
        ),
        migrations.RemoveField(
            model_name='translate',
            name='translate_module',
        ),
        migrations.AddField(
            model_name='translate_relation',
            name='card_translate',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='card.card'),
        ),
        migrations.AddField(
            model_name='translate_relation',
            name='menu_translate',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.menuitem'),
        ),
        migrations.AddField(
            model_name='translate_relation',
            name='translate_module',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='translate.translate'),
        ),
    ]
