# Generated by Django 4.2.3 on 2023-08-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_remove_translate_card_translate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='language_trans',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='translate.language'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='native_value',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
