# Generated by Django 4.2.3 on 2023-08-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0003_translate_language_trans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translate_relation',
            name='translate_module',
        ),
        migrations.AddField(
            model_name='translate_relation',
            name='translate',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='translate.translate'),
        ),
    ]
