# Generated by Django 4.2.3 on 2023-07-26 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(default='', max_length=1024)),
                ('text', models.TextField(default='', max_length=4096)),
                ('url', models.URLField()),
                ('order', models.IntegerField(default=0)),
                ('image', models.ImageField(default=None, upload_to='photos', verbose_name='image')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='card.cardstype')),
            ],
        ),
    ]
