# Generated by Django 4.2.3 on 2023-07-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_rename_cards_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='tittle',
            new_name='title',
        ),
    ]
