# Generated by Django 4.2.3 on 2024-04-29 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('submenu', models.BooleanField(default=False)),
                ('divider', models.BooleanField(default=False)),
                ('button', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, default=None, null=True, upload_to='icons', verbose_name='image')),
                ('create_date', models.DateField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.menuitem')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.menutype')),
            ],
        ),
    ]
