# Generated by Django 4.2.3 on 2023-07-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_elements_rename_menu_type_elementstype_delete_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementstype',
            name='orientation',
        ),
    ]
