# Generated by Django 4.2.3 on 2023-07-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_elementstype_orientation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='elementsType',
            new_name='MenuType',
        ),
    ]
