# Generated by Django 4.2.3 on 2023-07-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_elementstype_menutype'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='submenu',
            field=models.BooleanField(default=False),
        ),
    ]
