# Generated by Django 4.2.3 on 2023-07-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_elements_submenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutype',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='menutype',
            name='delete_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
