# Generated by Django 4.2.3 on 2023-07-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_menutype_create_date_menutype_delete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
