# Generated by Django 4.2.3 on 2023-07-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_elements_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.menutype'),
        ),
    ]
