# Generated by Django 4.2.3 on 2023-07-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_elements_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elements',
            new_name='Menu',
        ),
    ]
