# Generated by Django 4.2.3 on 2023-07-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_elements_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menutype',
            name='delete_date',
        ),
    ]
