# Generated by Django 4.2.3 on 2023-07-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_menutype_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.ImageField(default=None, upload_to='icons', verbose_name='image'),
        ),
    ]
