# Generated by Django 4.2.3 on 2023-07-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_menu_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='icons', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='submenu',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
