# Generated by Django 4.2.3 on 2023-07-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_menu_icon_alter_menu_submenu_alter_menu_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuItem',
        ),
    ]
