# Generated by Django 4.2.3 on 2024-04-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64)),
                ('days_of_use', models.DateField(auto_now_add=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
