# Generated by Django 4.2.3 on 2024-02-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=36)),
                ('days_of_test', models.PositiveIntegerField(default=15)),
                ('days_of_use_as_premiun', models.PositiveIntegerField(default=30)),
                ('start_date_for_test', models.DateField(auto_now_add=True)),
                ('start_date_for_premiun_use', models.DateField(auto_now_add=True)),
                ('tests_days_selected', models.BooleanField(default=False)),
                ('premiun_days_selected', models.BooleanField(default=False)),
            ],
        ),
    ]
