# Generated by Django 4.2.3 on 2024-04-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='days_of_use',
            field=models.DateField(blank=True, null=True),
        ),
    ]
