# Generated by Django 4.2.3 on 2024-04-30 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_days_of_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='days_of_use',
            field=models.DateField(default=datetime.datetime(2024, 5, 30, 15, 40, 7, 784384)),
        ),
    ]
